name: build iso

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ nasm make genisoimage python3 mtools

    - name: build img
      run: |
        VERSION=$(python3 build/maketool.py kver)
        echo "PROFAN_HDD=disk-$VERSION.bin" >> $GITHUB_ENV
        echo "PROFAN_ISO=profanOS-$VERSION.iso" >> $GITHUB_ENV
        echo "PROFAN_VER=profanOS v$VERSION" >> $GITHUB_ENV
        make srcdisk miso
        cd out/disk && zip -r ../../disk-build.zip * && cd ../..
        cp HDD.bin disk-$VERSION.bin
        cp HDD.bin profanOS-disk.bin
        cp profanOS.iso profanOS-$VERSION.iso
        cp profanOS.elf profanOS-kernel.elf

    - name: push iso to github
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: ${{ env.PROFAN_ISO }}
        destination_repo: 'esolangs/profanOS-build'
        destination_folder: 'post55-iso'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'new release'
  
    - name: push disk to github
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: ${{ env.PROFAN_HDD }}
        destination_repo: 'esolangs/profanOS-build'
        destination_folder: 'disk-build'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'new build'

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ${{ env.PROFAN_VER }}
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          ${{ env.PROFAN_ISO }}
          profanOS-kernel.elf
          profanOS-disk.bin
          disk-build.zip
